src/commands/force/source/retrieve.ts, test/commands/source/retrieve.test.ts
The postretrieve hook payload is now the file responses, which more closely matches the old
postsourceupdate hook, rather than the raw server response.
@W-9514884@
=> fix: postretrieve hook payload is now the file responses

messages/retrieve.json, src/formatters/retrieveResultFormatter.ts, test/commands/source/retrieveResponses.ts, test/formatters/retrieveResultFormatter.test.ts
Changes the retrieveResultFormatter to display warnings properly.  Slight restructuring for easier readability.   Adds a few unit tests.  Without these changes warnings were not being displayed and the output was confusing.
@W-9517801@
=> fix: display retrieve warnings

package.json, src/commands/force/source/convert.ts, src/commands/force/source/deploy.ts, src/commands/force/source/retrieve.ts, src/componentSetBuilder.ts, src/sourceCommand.ts, test/commands/source/componentSetBuilder.test.ts, test/commands/source/convert.test.ts, test/commands/source/deploy.test.ts, test/commands/source/retrieve.test.ts, yarn.lock
Sets a sourceApiVersion on the ComponentSet when deploying and retrieving, based on a sourceApiVersion set in sfdx-project.json.
@W-9604682@
=> fix: set sourceApiVersion on the ComponentSet

src/formatters/deployResultFormatter.ts, test/commands/source/deployResponses.ts, test/formatters/deployResultFormatter.test.ts
Deploy errors are in the JSON output but not being displayed in stdout in all cases. This was due to the code assuming that the response contained `DeployMessage[]` but it can also (unfortunately) return `DeployMessage`. 
Deploy errors are now displayed in the stdout table format.
@W-9596635@
=> fix: deploy errors are reported properly

src/commands/force/source/retrieve.ts, src/formatters/retrieveResultFormatter.ts, test/commands/source/retrieve.test.ts, test/commands/source/retrieveResponses.ts, test/formatters/retrieveResultFormatter.test.ts, test/nuts/seeds/retrieve.packagenames.seed.ts, yarn.lock
fixes retrieves with package name's output to list the package name, path, and source retrieved into that dir
matches toolbelt with the package section and JSON
differs from toolbelt by including the `Retrieved Source` section
@W-9584557@
=> fix: retrieve package names output

messages/report.json, src/commands/force/source/deploy/report.ts, src/formatters/deployReportResultFormatter.ts, test/commands/source/report.test.ts
the `deploy:report` command now uses the `--wait` flag
@W-9642428@
=> fix: deploy:report now respects the wait flag

src/componentSetBuilder.ts, test/commands/source/componentSetBuilder.test.ts, test/nuts/seeds/convert.seed.ts, test/nuts/seeds/deploy.metadata.seed.ts, test/nuts/seeds/retrieve.metadata.seed.ts
catches and transforms the SDR error for a missing metadata type to match the toolbelt's
should hopefully defer blame to the user rather than us
@W-9657211@
=> fix: missing metadata type error matches toolbelt

messages/cancel.json, messages/convert.json, messages/deploy.json, messages/open.json, messages/report.json, messages/retrieve.json
What does this PR do?
Adds back long description help for commands
What issues does this PR fix or reference?
@W-9735653@
=> fix: update command long descriptions

package.json, src/componentSetBuilder.ts, test/commands/source/componentSetBuilder.test.ts, test/nuts/create.nut.ts, yarn.lock
Fixes a bug where only source in the project was being retrieved even when requesting metadata that exists in the org.  If no matching files were found in the project it would work fine but if just 1 matching metadata was found it would only request that component.
E.g., `sfdx force:source:retrieve -m ApexClass` when there exists MyClass1 in the project and MyClass2 in the org, it would only retrieve MyClass1.
Similarly, `sfdx force:source:retrieve -m ApexClass:MyClass1,ApexClass:MyClass2` would also only retrieve MyClass1.
@W-9776828@
=> fix: wildcard metadata retrieves will now fetch source not in the project

.circleci/config.yml, test/formatters/deployResultFormatter.test.ts, test/formatters/retrieveResultFormatter.test.ts
updates the circle ci config so that source NUTs are run during the all-nuts workflow
@W-9799608@
=> ci: update circle ci config for all-nuts job

messages/deploy.json, src/commands/force/source/deploy.ts
puts back the parameter long descriptions for the force:source:deploy command.  
@W-9842098@
=> help: put back the long param descriptions for force:source:deploy

src/formatters/deployResultFormatter.ts, test/formatters/deployResultFormatter.test.ts
checks the server response for other issues not present in the `getFileResponse()` method from SDR and displays them alongside other deployment issues.
@W-9816657@ https://github.com/forcedotcom/cli/issues/1180
OLD
```
➜  sfdx force:source:deploy -m CustomField:Account.Name 
*** Deploying with SOAP API ***
Deploy ID: 0AfJ000001m2PoWKAU
SOURCE PROGRESS | ░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░ | 0/1 Components
ERROR running force:source:deploy:  Deploy failed.
```
NEW
```
➜  sfdx force:source:deploy -m CustomField:Account.Name 
*** Deploying with SOAP API ***
Deploy ID: 0AfJ000001m1diRKAQ
SOURCE PROGRESS | ░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░ | 0/1 Components
=== Component Failures [1]
Type   Name             Problem
─────  ───────────────  ──────────────────
Error  Account.NameNew …
```
=> fix: find server errors and display them with FileResponse errors

messages/open.json, src/formatters/openResultFormatter.ts
What does this PR do?
adds security warning for the output of source:open (AT in URL)
What issues does this PR fix or reference?
@W-9953835@
=> feat: warning label for source:open

messages/cancel.json, messages/convert.json, messages/delete.json, messages/report.json, messages/retrieve.json, src/commands/force/source/convert.ts, src/commands/force/source/delete.ts, src/commands/force/source/deploy/cancel.ts, src/commands/force/source/deploy/report.ts, src/commands/force/source/retrieve.ts
Puts back the long parameter descriptions that were lost when the force:source SDR commands were moved to their own plugin from toolbelt.
@W-9842098@
=> fix: add back missing long parameter descriptions for some force:source commands

package.json
use cross-env for test:nuts script
@W-0@
=> fix: use cross-env for test:nuts script

messages/deploy.json, src/deployCommand.ts, test/commands/source/report.test.ts
When a JsonParseError is thrown while reading `stash.json` for the deploy ID, the error is now caught, the file is renamed to stash.json_corrupted_<timestamp> and an error message is displayed that shows the parse failure and the location of the renamed stash.json so users can inspect the file, or possibly rebuild a valid file from the corrupt version.
@W-7837761@
Testing:
1. change stash.json to be invalid json
2. delete stash.json
3. change stash.json to be empty
In all cases an error should be thrown.  In 1 & 3 the stash.json file will be renamed so running the command again will not result in the same behaviour.
=> fix: handle a corrupt stash.json file

messages/md.describe.json, messages/md.list.json
Adds back a bit of missing command help after listmetadata and describemetadata were moved to plugin-source from toolbelt.
@W-10165523@
=> fix: add back missing help for listmetadata/describemetadata

command-snapshot.json, messages/cancel.json, messages/deploy.json, messages/md.cancel.json, src/commands/force/mdapi/deploy/cancel.ts, src/commands/force/source/delete.ts, src/commands/force/source/deploy.ts, src/commands/force/source/deploy/cancel.ts, src/commands/force/source/deploy/report.ts, src/commands/force/source/retrieve.ts, src/deployCommand.ts, src/sourceCommand.ts, test/commands/mdapi/cancel.test.ts, test/nuts/mdapi.nut.ts
moves `mdapi:deploy:cancel` command and messages
extends `plugin-source` base classes correctly
updates base classes to support `MDAPI_DEPLOY` stash key
adds UTs
adds NUTs
`source:deploy:cancel`,`source:deploy:report`, `mdapi:deploy:cancel` all validate the passed in deploy ID parameter
fixes issue when stash is missing a requested key/value
@W-9603715@
=> fix: add mdapi:deploy:cancel command, refactor base classes to support MDAPI and SOURCE stash keys

src/commands/force/mdapi/listmetadata.ts, test/nuts/mdapi.nut.ts
only include the folder ListMetadataQuery for jsForce's connection.metadata.list when it's a folder type.  Even an undefined folder value causes problems for the ListView type.
@W-10203090@
=> fix: conditionally include folder

.circleci/config.yml, package.json
Enables deploy async NUTs.
There were disabled a few months ago because of a memory leak, today I was able to run them locally (`test:nuts:deploy:async`) on my mac and also passed on linux/win ✅
Pretty sure the bug causing the mem leak was addressed in some SDR version 😄 
@W-9800765@
=> chore: enable deploy async NUTs

.gitignore
Reverts salesforcecli/plugin-source#352
```
test/nuts/generated/
```
is still needed for plugin-source
=> Revert "chore: sync .gitignore"

messages/retrieve.json
Adds missing quotes in two examples in --help of source:retrieve
@W-10457407@
=> fix: missing quotes in --help for source:retrieve

src/commands/force/mdapi/beta/retrieve.ts, test/commands/mdapi/retrieve.test.ts, test/nuts/mdapi.nut.ts, test/nuts/seeds/deploy.async.seed.ts, test/nuts/seeds/retrieve.manifest.seed.ts
Makes the `zipfilename` parameter short char consistent between `mdapi:retrieve` and `mdapi:retrieve:report`
Fixes a few tests
@W-0@
=> fix: make retrieve param consistent and fix tests

test/nuts/seeds/deploy.async.seed.ts
temporarily disable async deploy NUTs due to memory issues on Windows
@W-0@
=> fix: temporarily disable async deploy NUTs

command-snapshot.json, package.json, src/commands/force/source/pull.ts, src/commands/force/source/push.ts, src/commands/force/source/status.ts, src/commands/force/source/tracking/clear.ts, src/commands/force/source/tracking/reset.ts, src/trackingFunctions.ts, test/nuts/trackingCommands/basics.nut.ts, test/nuts/trackingCommands/conflicts.nut.ts, test/nuts/trackingCommands/deployRetrieveDelete.nut.ts, test/nuts/trackingCommands/forceIgnore.nut.ts, test/nuts/trackingCommands/lwc.nut.ts, test/nuts/trackingCommands/mpd-non-sequential.nut.ts, test/nuts/trackingCommands/mpd-sequential.nut.ts, test/nuts/trackingCommands/remoteChanges.nut.ts, test/nuts/trackingCommands/resetClear.nut.ts, yarn.lock
requires https://github.com/forcedotcom/source-tracking/pull/136
should go out with https://github.com/salesforcecli/toolbelt/pull/225
GA the new versions of the tracking commands
prevents some edge cases of undefined that would cause problems for cli-ux/table
2nd try at [@W-10830392@](https://gus.lightning.force.com/a07EE00000sWQDXYA4)
=> feat: GA new tracking commands

src/formatters/deployResultFormatter.ts
Import `coverageUtils` from parent folder instead of `../../src/`.
This is causing `sfdx` to fail because the compiled js doesn't know about the `src` folder.
@W-0@
=> fix: import coverageUtils from parent folder

src/coverageUtils.ts, test/coverageUtils.test.ts
Math.min with no params is Infinity. Default to 1 when array is empty
@W-11221748@
=> fix: default min line number to 1 when 100 pct coverage

src/commands/force/mdapi/retrieve.ts, test/commands/mdapi/retrieve.test.ts
Exclude passing a sourcepath to the ComponentSetBuilder when the `unpackaged` flag is set.  The `unpackaged` flag is the path to the manifest and the command should only use the manifest, not consider any local source path.
@W-11588116@
=> fix: exclude sourcepath from component set builder

messages/deploy.json, messages/md.deploy.json, messages/push.json, src/commands/force/source/push.ts, src/formatters/deployResultFormatter.ts, src/formatters/mdapi/mdDeployResultFormatter.ts, src/formatters/source/pushResultFormatter.ts, test/formatters/deployResultFormatter.test.ts, test/formatters/mdDeployResultFormatter.test.ts, test/formatters/pushResultFormatter.test.ts
When a deploy fails without any component failures the command was not showing the errorMessage field that is set on the response.  This PR adds that error message to the error thrown by the command.
@W-11905229@
For Testing:
Deploy code that will cause a GACK.  I have a repro for you.
`sfdx force:source:deploy -p force-app`
`sfdx force:mdapi:deploy`
`sfdx force:source:push`
=> fix: display error message from response

package.json, src/commands/force/source/push.ts, yarn.lock
removes printing which api version is used per package per package.
now properly prints which api version is used per package, only once
BEFORE:
```
Pushing v55.0 metadata to [test-ovsqkpand1dp@example.com](mailto:test-ovsqkpand1dp@example.com) using the v56.0 SOAP API
DEPLOY PROGRESS | ████████████████████████████████████████ | 2/2 Components
Pushing v55.0 metadata to [test-ovsqkpand1dp@example.com](mailto:test-ovsqkpand1dp@example.com) using the v56.0 SOAP API
Pushing v55.0 metadata to [test-ovsqkpand1dp@example.com](mailto:test-ovsqkpand1dp@example.com) using the v56.0 SOAP API
DEPLOY PROGRESS | ████████████████████████████████████████ | 1/1 Components
Pushing v55.0 metadata to [test-ovsqkpand1dp@example.com](mailto:test-ovsqkpand1dp@example.com) using the v56.0 SOAP API
Pushing v55.0 …
```
=> fix: only listen to events once per package

package.json, test/nuts/partialBundleDelete.nut.ts, yarn.lock
Modifies existing NUTs to ensure forceignored files are not deleted during a partial bundle delete retrieve.
@W-12460543@
=> fix: enhance partial bundle delete tests for forceignored files

src/commands/force/source/deploy.ts, src/formatters/deployProgressStatusFormatter.ts, test/formatters/deployProgressStatusFormatter.ts
When the `force:source:deploy` command is run with the `--verbose` flag and the progress bar is turned off with `SFDX_USE_PROGRESS_BAR=false` the deploy status is output with every poll.  With this change, CI systems that have low output timeouts will not exit for long-running deploys, where the command does not output for many minutes.
https://github.com/forcedotcom/cli/issues/1839
@W-12234469@
=> feat: verbose deploys without progress bar update with each poll

package.json
Removes a yarn script that calls a nut that migrated to `plugin-deploy-retrieve`
=> Remove nuts:delete script

messages/md.deployreport.md, messages/report.md, src/commands/force/mdapi/deploy/report.ts, src/commands/force/mdapi/retrieve/report.ts, src/commands/force/source/deploy/report.ts
sets a default on the `wait` flag on both mdapi report commands.
[@W-12992146@](https://github.com/forcedotcom/cli/issues/2042)
=> fix: default for wait on mdapi:report commands

src/commands/force/source/deploy.ts, src/commands/force/source/pull.ts, src/commands/force/source/push.ts, src/commands/force/source/retrieve.ts, src/commands/force/source/status.ts, src/sourceCommand.ts, src/trackingFunctions.ts
while we still had toolbelt around, these commands would use STL's compatibility code to check which version of tracking fils were present, to give users helpful messages about how not to mix old and new local tracking files.
This takes all of that out
@W-12293678@
=> feat: remove STL compatibility features for old toolbelt tracking files

package.json, src/commands/force.ts, yarn.lock
bump `proxy-agent` to latest major version and remove `proxy-from-env` dep since it is now redundant with latest `proxy-agent`
@W-13546885@
=> fix: bump proxy-agent to latest major version

test/commands/source/retrieve.test.ts
updates retrieve.test.ts to use new TestSetup features from sfdx-core
=> fix: update retrieve test to use new test setup features

package.json, test/nuts/mdapi.nut.ts, test/nuts/trackingCommands/forceIgnore.nut.ts, yarn.lock
> requires https://github.com/salesforcecli/cli-plugins-testkit/pull/539
templates goes to v59, but the org might not support it for a few weeks.
This sets the api version on the created classes and the testkit project sourceApiVersion
[@W-13913391@](https://gus.lightning.force.com/lightning/r/ADM_Work__c/a07EE00001XvsAqYAJ/view)
kinda caused by our rollout of [@W-13586057@](https://gus.lightning.force.com/a07EE00001Tl80JYAR)
example of the problem this solves: https://github.com/salesforcecli/cli/actions/runs/5804183268/job/15734000727
=> test: api version on projects

package.json, src/formatters/source/pullFormatter.ts, src/formatters/source/pushResultFormatter.ts, src/formatters/source/statusFormatter.ts, yarn.lock
at some point, node has gotten better typing for process.exitCode.  strings are no longer allowed
https://github.com/forcedotcom/source-deploy-retrieve/actions/runs/8955181731/job/24595639380?pr=1305
=> fix: node types for process exitCode don't allow string

README.md, messages/cancel.md, messages/deploy.md, messages/md.cancel.md, messages/md.deploy.md, messages/md.deployreport.md, messages/md.retrieve.md, messages/pull.md, messages/push.md, messages/report.md, messages/retrieve.md, messages/status.md, package.json, src/commands/force.ts, src/commands/force/mdapi/retrieve/report.ts
put message on all commands in plugin-source saying when they'll be removed from the CLI
@W-16091770@
=> feat: removal notice

test/nuts/seeds/deploy.metadata.seed.ts, test/nuts/seeds/retrieve.metadata.seed.ts, test/nuts/seeds/retrieve.retrievetargetdir.seed.ts
test failures on https://github.com/forcedotcom/source-deploy-retrieve/pull/1374 
are because the nut specifies the error name, which SDR is changing.
https://github.com/forcedotcom/source-deploy-retrieve/actions/runs/10081843723/job/27874888122?pr=1374
[@W-16324102@](https://gus.lightning.force.com/a07EE00001xOHgbYAG)
=> test: remove error name assertions (let SDR handle)
