src/commands/force/source/deploy.ts, src/formatters/deployProgressBarFormatter.ts, src/formatters/deployProgressStatusFormatter.ts, src/formatters/deployResultFormatter.ts, src/formatters/progressFormatter.ts, test/commands/source/deploy.test.ts
Adds the missing functionality of displaying the progress of status when SFDX_USE_PROGRESS_BAR is set to false.
@W-9543714@
=> Sfdx user progress bar status bug

src/formatters/retrieveResultFormatter.ts, test/formatters/retrieveResultFormatter.test.ts, test/nuts/seeds/retrieve.packagenames.seed.ts
adds a space between components and package names in output
changes package for NUTs
enables 2 tests
=> fix: minor package fixes

messages/deploy.json, src/commands/force/source/deploy.ts, test/commands/source/deploy.test.ts
Adds a check to ensure user has provided a required flag before deploying source.
@W-9586707@
=> fix: throw deploy error when missing required params

package.json
=> fix: bump to 1.0.5

package.json, test/nuts/testMatrix.ts, yarn.lock
=> fix: bump SDR to 4.0.2

package.json, test/nuts/create.nut.ts, yarn.lock
fixes the NUTs for https://github.com/forcedotcom/source-deploy-retrieve/pull/446
@W-9816625@
=> test: fix NUTs for SDR PR 446

package.json, yarn.lock
bumps SDR to 4.4.1 for functions fix
=> fix: bump SDR to 4.4.1

package.json, test/tsconfig.json, yarn.lock
=> chore: bump deps

package.json, yarn.lock
=> fix: bump stl for customField status and pull

test/nuts/trackingCommands/basics.nut.ts, test/nuts/trackingCommands/conflicts.nut.ts, test/nuts/trackingCommands/remoteChanges.nut.ts, test/nuts/trackingCommands/resetClear.nut.ts
nuts-only.  Uses main branch of test repo
=> test: conflict nuts use more recent ebikes

messages/deploy.json
apply Juliet's fix to `source:deploy` too 
@W-0@
=> chore: fix message

test/nuts/mdapi.nut.ts
Sometimes the async retrieve:report NUT was finishing faster than expected so the expectations were failing.  This adds more flexibility to the test for this scenario.
E.g., it would report:
```
retrieves report (async):
AssertionError: expected { done: true, …(5) } to have property 'done' of false, but got true
+ expected - actual
-true
+false
at Context.<anonymous> (test/nuts/mdapi.nut.ts:311:33)
```
@W-0@
=> test: make retrieve async nut more robust

command-snapshot.json, package.json, src/commands/force/source/beta/pull.ts, src/commands/force/source/beta/push.ts, src/commands/force/source/beta/status.ts, src/commands/force/source/beta/tracking/clear.ts, src/commands/force/source/beta/tracking/reset.ts, src/trackingFunctions.ts, test/nuts/trackingCommands/basics.nut.ts, test/nuts/trackingCommands/conflicts.nut.ts, test/nuts/trackingCommands/deployRetrieveDelete.nut.ts, test/nuts/trackingCommands/forceIgnore.nut.ts, test/nuts/trackingCommands/lwc.nut.ts, test/nuts/trackingCommands/mpd-non-sequential.nut.ts, test/nuts/trackingCommands/mpd-sequential.nut.ts, test/nuts/trackingCommands/remoteChanges.nut.ts, test/nuts/trackingCommands/resetClear.nut.ts, yarn.lock
reverts `beta` GA
@W-10803688@
=> fix: revert beta GA

command-snapshot.json, package.json, src/commands/force.ts, test/nuts/force.nut.ts, tsconfig.json, yarn.lock
Add cmd force (moved from plugin-info)
@W-10847992@
=> fix: move command force to plugin-source

.circleci/config.yml, package.json, yarn.lock
bump stl for graceful
dependabot-automerge w/ squash to prevent https://app.circleci.com/pipelines/github/salesforcecli/plugin-source/3091/workflows/cbc30c06-38f1-428a-ba0d-e7a86bf84ea0/jobs/23852
[@W-10899802@](https://gus.lightning.force.com/a07EE00000tdwd2YAA)
=> fix: bump stl for graceful

package.json, yarn.lock
[@W-10899802@](https://gus.lightning.force.com/a07EE00000tdwd2YAA)
=> fix: fix from stl

package.json, yarn.lock
bumps to latest SDR library
@W-0@
=> fix: bump to latest sdr

test/nuts/trackingCommands/basics.nut.ts, test/nuts/trackingCommands/conflicts.nut.ts, test/nuts/trackingCommands/lwc.nut.ts, test/nuts/trackingCommands/remoteChanges.nut.ts
fix nuts for changes in ebikes
[@W-11111430@](https://gus.lightning.force.com/a07EE00000wXoaYYAS)
=> test: nut updates for ebikes-lwc (utam)

test/nuts/trackingCommands/consts.ts
Updates ebikes pushed items count for recent updates https://github.com/trailheadapps/ebikes-lwc/pull/419
Loosely tied to [@W-11358405@](https://gus.my.salesforce.com/apex/ADM_WorkLocator?bugorworknumber=W-11358405)
=> ebikes nuts fix

package.json, yarn.lock
bumps SDR to include [this fix](https://github.com/forcedotcom/source-deploy-retrieve/pull/659) in the plugin.
@W-0@
=> fix: bump SDR

package.json, yarn.lock
=> fix: caret for jsforce

test/commands/mdapi/convert.test.ts, test/commands/mdapi/listmetadata.test.ts
remove 2 ut that fail due to oclif error message changes
=> test: remove tests depending on oclif require flag validation [skip-validate-pr]

package.json, yarn.lock
bumps apex-node to include fix for https://github.com/forcedotcom/cli/issues/1581
=> fix: bump apex-node

.github/workflows/test.yml
Calls single unit test files in GHA. See https://github.com/salesforcecli/github-workflows/pull/12
(This will fail until that is merged ^)
[@W-11949808@](https://gus.my.salesforce.com/apex/ADM_WorkLocator?bugorworknumber=W-11949808)
=> GHA unit test change

package.json, yarn.lock
bump the version of SDR and recreate the lock file
@W-11111111@
=> fix: bump SDR and regen lock file

.github/workflows/test.yml
restore test parallelization
[@W-11976301@](https://gus.my.salesforce.com/apex/ADM_WorkLocator?bugorworknumber=W-11976301)
=> test: restore test parallelization

package.json, src/commands/force.ts, src/commands/force/source/delete.ts, src/formatters/deployProgressBarFormatter.ts, src/sourceCommand.ts, src/types.ts, test/commands/mdapi/cancel.test.ts, test/commands/mdapi/convert.test.ts, test/commands/mdapi/describemetadata.test.ts, test/commands/mdapi/listmetadata.test.ts, test/commands/mdapi/retrieve.test.ts, test/commands/mdapi/retrieveReport.test.ts, test/commands/source/cancel.test.ts, test/commands/source/convert.test.ts, test/commands/source/delete.test.ts, test/commands/source/deploy.test.ts, test/commands/source/open.test.ts, test/commands/source/report.test.ts, test/commands/source/retrieve.test.ts, yarn.lock
Uses sf-plugins-core v2 and oclif/core v2
@W-10791948@
=> feat: use latest oclif/core

package.json, src/formatters/source/pushResultFormatter.ts, test/commands/source/testConsts.ts, yarn.lock
copy of https://github.com/salesforcecli/plugin-source/pull/726 to run NUTs
but also bumps SDR
@W-12502730@
=> feat: support for ExperiencePropertyType Bundle

test/nuts/partialBundleDelete.nut.ts
minor changes to the test to get it to pass on windows
@W-00000000@
=> chore: fix partial bundle delete nut

messages/cancel.md, messages/deploy.md, messages/deployCommand.md, messages/ignored_list.md, messages/md.cancel.md, messages/md.deploy.md, messages/md.deployreport.md, messages/md.retrieve.md, messages/pull.md, messages/push.md, messages/report.md, messages/retrieve.md, messages/stash.md, messages/status.md, src/commands/force/mdapi/deploy.ts, src/commands/force/mdapi/deploy/cancel.ts, src/commands/force/mdapi/deploy/report.ts, src/commands/force/mdapi/retrieve.ts, src/commands/force/mdapi/retrieve/report.ts, src/commands/force/source/deploy.ts, src/commands/force/source/deploy/cancel.ts, src/commands/force/source/deploy/report.ts, src/commands/force/source/ignored/list.ts, src/commands/force/source/pull.ts, src/commands/force/source/push.ts, src/commands/force/source/retrieve.ts, src/commands/force/source/status.ts
What does this PR do?
edits/cleans up sf-ized messages
What issues does this PR fix or reference?
@W-12623662@
replaces https://github.com/salesforcecli/plugin-source/pull/778 with the correct base branch
=> fix: regen yarn.lock, cherry-pick Juliet's messages

messages/cancel.md, messages/deploy.md, messages/md.cancel.md, messages/md.deploy.md, messages/md.deployreport.md, messages/md.retrieve.md, messages/pull.md, messages/push.md, messages/report.md, messages/retrieve.md, messages/status.md
Softens the deprecation message to be "in the future" rather than "soon".
@W-12623662@
=> fix: change "deprecate soon" to "in the future"

package.json, test/nuts/digitalExperienceBundle/constants.ts, test/nuts/digitalExperienceBundle/deb.manifest.nut.ts, test/nuts/digitalExperienceBundle/deb.metadata.nut.ts, test/nuts/digitalExperienceBundle/deb.sourcepath.nut.ts, test/nuts/digitalExperienceBundle/deb.tracking.nut.ts, test/nuts/digitalExperienceBundle/helper.ts, test/nuts/digitalExperienceBundle/store/manifests/de-view-home-of-deb-b-package.xml, yarn.lock
Adding NUTs for language variant deletion in a DigitalExperience component.
[@W-12749906@](https://gus.lightning.force.com/a07EE00001NtCyGYAV)
=> test: add nuts for de language variant deletion

test/nuts/seeds/deploy.sourcepath.seed.ts
allows both variants of the error message.  
fix https://github.com/forcedotcom/source-deploy-retrieve/actions/runs/4612195262/jobs/8152853451
needed for part 6 of @W-12671663@
=> chore: allow error message change

package.json, yarn.lock
bumps STL to 3.1.0
@W-12293678@
=> fix: bump STL

package.json, src/commands/force/mdapi/deploy.ts, src/commands/force/mdapi/deploy/report.ts, src/commands/force/source/deploy.ts, src/commands/force/source/deploy/report.ts, src/commands/force/source/push.ts, src/deployCommand.ts, test/commands/source/deploy.test.ts, test/nuts/mdapi.nut.ts, yarn.lock
keep plugin-source from referring to a deprecated config
[@W-13048680@](https://gus.lightning.force.com/a07EE00001PcD2iYAF)
=> fix: avoid warning from asking for old config

package.json, yarn.lock
=> fix(deps): bump sdr

test/nuts/partialBundleDelete.nut.ts
update partial bundle delete tests for Dreamhouse source changes
=> fix: update partial bundle delete tests for Dreamhouse source changes

package.json, yarn.lock
bump SDR for deduped fileResponses
@W-14262002@
=> fix(deps): bump SDR for deduplicated fileResponses

package.json, test/nuts/trackingCommands/remoteChanges.nut.ts, yarn.lock
bump stl
maybe help with https://github.com/salesforcecli/plugin-deploy-retrieve/actions/runs/6552529996/job/17796079363 ?
=> fix(deps): bump stl

src/formatters/source/deployAsyncResultFormatter.ts, test/commands/source/deployResponses.ts, test/formatters/retrieveResultFormatter.test.ts
cloneJson => structuredClone
@W-14726723@
=> refactor:  cloneJson => structuredClone

src/commands/force/mdapi/deploy.ts, src/commands/force/mdapi/deploy/cancel.ts, src/commands/force/mdapi/deploy/report.ts, src/commands/force/mdapi/retrieve.ts, src/commands/force/mdapi/retrieve/report.ts, src/commands/force/source/deploy.ts, src/commands/force/source/deploy/cancel.ts, src/commands/force/source/deploy/report.ts, src/commands/force/source/pull.ts, src/commands/force/source/push.ts, src/commands/force/source/retrieve.ts, src/commands/force/source/status.ts
marks deprecated commands as hidden
[keep them out of docs, autocomplete, etc]
@W-14739853@
=> feat: hide deprecated commands

src/formatters/source/pushResultFormatter.ts
while digging around telemtry because of https://github.com/forcedotcom/cli/issues/2697 I found another TypeError that's happening.
see github comments  for explanation
=> fix: remove an undefined TypeError

test/nuts/trackingCommands/consts.ts, test/nuts/trackingCommands/remoteChanges.nut.ts
2 files removed for spring24
see https://github.com/trailheadapps/ebikes-lwc/pull/649/files#diff-df6b944748317c72500f189cb37b829f24b3091e79593047d2b6ebf5eb3006fc
https://github.com/forcedotcom/source-deploy-retrieve/actions/runs/7891542653/job/21536191962?pr=1218
=> test: 209 items for spring24 release

README.md, command-snapshot.json, package.json, src/deployCommand.ts, src/formatters/deployReportResultFormatter.ts, src/formatters/deployResultFormatter.ts, src/formatters/mdapi/mdDeployAsyncResultFormatter.ts, src/formatters/mdapi/mdDeployResultFormatter.ts, src/formatters/retrieveFormatter.ts, src/formatters/source/pullFormatter.ts, src/formatters/source/statusFormatter.ts, src/stash.ts, src/trackingFunctions.ts, test/commands/mdapi/retrieve.test.ts, test/commands/mdapi/retrieveReport.test.ts, test/commands/source/cancel.test.ts, test/commands/source/deploy.test.ts, test/commands/source/report.test.ts, test/commands/source/retrieve.test.ts, yarn.lock
Add `--flags-dir` to all commands by bumping @salesforce/sf-plugins-core to v8
=> feat: bump sf-plugins-core

package.json, yarn.lock
@W-15354956@
bump apex-node that required a major release, but affected areas not used by plugin-source
=> fix: bump apex-node to v4

package.json, yarn.lock
=> fix(deps): bump apex-node off of beta
